import { Plan } from "./enums/planEnums";

export const plans = [
    {
        title: "Free Trial",
        price: "Free",
        description: "Start Your Free Trial",
        features: ["Example Feature Number 1"],
        actionLabel: "Get Started",
        planName: Plan.Free,
        isYearly: null,
    },
    {
        priceId : "price_1PtnWwKtFzpP1K4zlxZVmmMl",
        title: "Basic Monthly",
        price : 10,
        link: "test_dR63fe55h06E32E9AD",
        description: "Essential features you need to get started",
        features: ["Example Feature Number 1", "Example Feature Number 2", "Example Feature Number 3"],
        actionLabel: "Get Started",
        planName: Plan.Basic,
        isYearly: false,
    },
    {   
        priceId : "price_1PtnWwKtFzpP1K4znu6rvT4X",
        title: "Basic Yearly",
        price: 100,
        link: "test_cN203269l1aIfPqeUY",
        description: "Essential features you need to get started",
        features: ["Example Feature Number 1", "Example Feature Number 2", "Example Feature Number 3"],
        actionLabel: "Get Started",
        planName: Plan.Basic,
        isYearly: true
    },
    {
        priceId: "price_1PtnZIKtFzpP1K4ztRHqlmLj",
        title: "Pro Monthly",
        price: 25,
        link: "test_3cseXWdBN8Da46I001",
        description: "Perfect for owners of small & medium businessess",
        features: ["Example Feature Number 1", "Example Feature Number 2", "Example Feature Number 3"],
        actionLabel: "Get Started",
        popular: true,
        planName: Plan.Pro,
        isYearly: false,
    },
    {
        priceId: "price_1PtnZIKtFzpP1K4zc3ycmFLi",
        title: "Pro Yearly",
        price: 250,
        link: "test_3cseXW55h06E0Uw28a",
        description: "Perfect for owners of small & medium businessess",
        features: ["Example Feature Number 1", "Example Feature Number 2", "Example Feature Number 3"],
        actionLabel: "Get Started",
        popular: true,
        planName: Plan.Pro,
        isYearly: true,
    },
    {
        title: "Enterprise",
        price: "Custom",
        description: "Dedicated support and infrastructure to fit your needs",
        features: ["Example Feature Number 1", "Example Feature Number 2", "Example Feature Number 3", "Super Exclusive Feature"],
        actionLabel: "Contact Sales",
        exclusive: true,
        planName: Plan.Pro,
        isYearly: null,
    },
];
